version: '3.9'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: appointment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: tmanmoseri1@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:8081"
volumes:
  pgdata:
